### ISSUE TITLE
Failed to cherry-pick PR #981: Submarine Itty Bitty Baby Patch

### ISSUE THREAD

**Issue by SimpleStation14** [Simple-Station/Einstein-Engines#100]
## Failed to cherry-pick PR: cannot create a tree from a not fully merged index.; class=Index (10); code=Unmerged (-10)
PR body below

####### `d78050be8aaa5d5afa0924604867ee8dc7915845`

PR opened by <img src="https://avatars.githubusercontent.com/u/52761126?v=4" width="16"/><a href="https://github.com/rosieposieeee"> rosieposieeee</a> at 2024-03-20 03:37:36 UTC
PR merged by <img src="https://avatars.githubusercontent.com/u/19864447?v=4" width="16"/><a href="https://github.com/web-flow"> web-flow</a> at 2024-03-20 05:07:35 UTC

---

PR changed 2 files with 9915 additions and 9874 deletions.

The PR had the following labels:
- Status: Needs Review
- Changes: Map

---

<details open="true"><summary><h1>Original Body</h1></summary>

> 
> 
> 
> The vile & Traitorous Velcroboy has Demanded of me minor changes.
> 
> - fixed fax machines & cameras missing names
> - made brig & perma doors close each other instead of bolt
> - added the recycler reclaimer thing whatever its called to disposals
> - removed unfinished jani switchboard
> - flattened out brig very niceys
> - gave the clown two pies
> - clown & mime lockers are no longer unanchorable. get fucked kidnapping clowns

</details>

**Comment by rosieposieeee** [comment]
![image](https://github.com/Simple-Station/Einstein-Engines/assets/52761126/ba7ca8f4-9f0d-43a3-9c94-3bc2fa3384c9)

**Comment by VMSolidus** [comment]
> ![image](https://private-user-images.githubusercontent.com/52761126/321105941-ba7ca8f4-9f0d-43a3-9c94-3bc2fa3384c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3MjUxNjYsIm5iZiI6MTcxMjcyNDg2NiwicGF0aCI6Ii81Mjc2MTEyNi8zMjExMDU5NDEtYmE3Y2E4ZjQtOWYwZC00M2EzLTljOTQtM2JjMmZhMzM4NGM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDA0NTQyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzMDA1YzcwYjk0MDJhYmQ3ZjFjM2FhYTRmNWIzZTcwYWY3Y2NlNGI2YmM2ZmU2ZDg4NTkxMzdiZjVhZmQwZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.q7vytGtGyHN1AmBbwtvRunG3WlUd4IgFLgp2BTcc3Ds)

_Wheeeeeeeeeeeeeeeeeeeeeeeeeeeeeze_

**Comment by VMSolidus** [comment]
Closing because we won't be incrementally updating Delta-V maps here, we're better off doing periodic merges of full map versions.
