### ISSUE TITLE
Failed to cherry-pick PR #987: Subpatch 3/20/24

### ISSUE THREAD

**Issue by SimpleStation14** [Simple-Station/Einstein-Engines#101]
## Failed to cherry-pick PR: cannot create a tree from a not fully merged index.; class=Index (10); code=Unmerged (-10)
PR body below

####### `5e32b2f6f67425260501f014d1456a1e88d178d6`

PR opened by <img src="https://avatars.githubusercontent.com/u/52761126?v=4" width="16"/><a href="https://github.com/rosieposieeee"> rosieposieeee</a> at 2024-03-21 05:40:38 UTC
PR merged by <img src="https://avatars.githubusercontent.com/u/19864447?v=4" width="16"/><a href="https://github.com/web-flow"> web-flow</a> at 2024-03-21 06:10:41 UTC

---

PR changed 3 files with 11753 additions and 10694 deletions.

The PR had the following labels:
- Status: Needs Review
- Changes: Map

---

<details open="true"><summary><h1>Original Body</h1></summary>

> 
> 
> 
> ## About the PR
> 
> 
> Evac shuttle's fixed, missing tiny fan by the park is fixed, bar got its space window back, singulo area now has a backup generator, vault got a quick redesign, + one billion tiny other things like misc cables and lights and shit.
> 
> **Changelog**
> 
> :cl:
> - fix: More fixes for Submarine! Thank you everyone for your feedback.

</details>

**Comment by VMSolidus** [comment]
Closing because we won't be incrementally updating Delta-V maps here, we're better off doing periodic merges of full map versions.
