### ISSUE TITLE
antags can get objective to steal HoS x-01 when they dont have it equipped

### ISSUE THREAD

**Issue by starch70** [Simple-Station/Einstein-Engines#1076]
# Description
antags can get a objective to steal the X-01 even when you have esword or c20 or whatever equipped as HoS

# Reproduction
1: be antag
2: get objective to x-01
3: fail already because x-01 is dogshit and HoS probably has esword equipped instead

# Expected behavior
1: roll antag
2: get objective to steal the unique weapon HoS is actually using

# Media

![image](https://github.com/user-attachments/assets/27397b58-c0f1-4a2c-a684-8b6f4f696251)
![image](https://github.com/user-attachments/assets/41490a36-618f-428a-bf68-51edb7e004d4)

# Additional context

**Comment by FoxxoTrystan** [comment]
@VMSolidus can you take a look as you added this.

**Comment by stellar-novas** [comment]
@DangerRevolution why the thumbs down?
