### ISSUE TITLE
Salvage Shuttle needs to have the two latejoin spawners removed

### ISSUE THREAD

**Issue by bruhmogus** [Simple-Station/Einstein-Engines#1099]
# Description
The latejoin spawners on the salvage shuttle can spawn any role, including those without salvage access.

# Reproduction
1. Latejoin as any role
2. Get stuck

# Expected behavior
Latejoining should never send you to an area you can't leave.

# Media
![20241019093137_1](https://github.com/user-attachments/assets/bd304853-3b4a-4538-b0bb-11afffc2d678)

# Additional context
I really don't know why those are there.

**Comment by Erisfiregamer1** [comment]
<img width="272" alt="image" src="https://github.com/user-attachments/assets/79ec4ed5-d870-453a-b79a-25be1abed025">
is that a me reference?!
