### ISSUE TITLE
shadowkin don't get ejected on hit

### ISSUE THREAD

**Issue by dge21** [Simple-Station/Einstein-Engines#1122]
# Description
Shadowkin don't get ejected out of shade form on hit properly

# Reproduction

1. Be a shadowkin
2. enter shade form
3. get shot
4. stay shaded

# Expected behavior

1. Be a shadowkin
2. enter shade form
3. get shot
4. get unshaded

# Media
none

# Additional context

There's a fluffly little guy in my computer

**Comment by FoxxoTrystan** [comment]
Okay additional questions @dge21 .

Excepted Behavior is when in shade from you cannot get shot.
Can you get shot in shade form?

**Comment by dge21** [comment]
you can

I've been both shot by a laser and blown up by a seismic charge, taking damage from both

**Comment by FoxxoTrystan** [comment]
Shadowkin get yeeted out of the dark if critted or dead or the use of bluespace crystals.
Nows that i got that information i supose the server is running on "EtherealPass" false, meaning that your collision is the same as a flying mod, currently its is normal that they do not get ejected on hit but this may change.

**Comment by dge21** [comment]
ah, well I was told to open an issue about this

I do think its better for them to not be ejected on hit

**Comment by FoxxoTrystan** [comment]
Thanks for opning the Issue, this still helps, were gona talk about it as were gona do some changes to kin in the future.
