### ISSUE TITLE
Italicize text when whispering

### ISSUE THREAD

**Issue by SkippyMcSkips** [Simple-Station/Einstein-Engines#1130]
# Description

Currently, whispering's only indication is in the chat window. This feels clunky to me and could be improved by italicizing and darkening the font both over the player's head, and the whole text string in the chat window. It's currently only italicizing the player's name and the word "whispers" in the chat window.

# Media

Example on Goob Station 1, showing how whispering is handled
<img width="251" alt="whispering" src="https://github.com/user-attachments/assets/e651f6b7-b84e-4cf1-917f-20f63e124eac">

Example on EE-based Goob Station 2 (MRP Edition)
![image](https://github.com/user-attachments/assets/6033f9ba-99d7-4478-bc68-e382b2d5b274)

![image](https://github.com/user-attachments/assets/44776d72-e258-42db-a4df-7a7849b8b419)

**Comment by angelofallars** [comment]
Fixed with https://github.com/Simple-Station/Einstein-Engines/pull/1294
