### ISSUE TITLE
Rebranding to Einstein Engines

### ISSUE THREAD

**Issue by VMSolidus** [Simple-Station/Einstein-Engines#12]
We have a repository with a surprising amount of things in it that makes the claim that this repository is DeltaV. We need to remove basically everything from this repository that says "This is DeltaV". Since all of that is hiding basically everywhere in the repository, this is going to be a fun cooperative assignment. So here's a few tasks that need to be performed:

- [ ] Move the entire contents of DeltaV, Nyanotrasen, and Simplestation folders into appropriate core code folders
- [ ] Make improvements to the actual organization of these folders so people can find code again. Ex: Species folder should have a folder for every species in the game, and contain for example Harpy/Components and Harpy/Systems. All Harpy code is then to be moved to said folders. That way if someone wants to look at code for Harpies(Of which there is a lot!), they only need to go to the Harpy folder to find everything they need. 
- [ ] Enforce a Systems & Components folder split for relevant systems. 
- [ ] Maybe, potentially, possibly do the same with prototypes.
- [ ] Gradually remove references to code being from DeltaV, this will require a very precise and careful hand.

**Comment by DangerRevolution** [comment]
@VMSolidus update?

**Comment by VMSolidus** [comment]
Closed as outdated, we have since significantly changed our policies.
