### ISSUE TITLE
Engine update caused issue with opening multiple bags

### ISSUE THREAD

**Issue by bruhmogus** [Simple-Station/Einstein-Engines#1242]
# Description

Opening a bag while in another bag causes the bag menu to disappear and the bag to remain "open"

# Reproduction

1. Open bag 1
2. Open bag 2
3. See your inventory disappear
4. Press "Close bag"

# Expected behavior

1. Open bag 1
2. Open bag 2
3. See bag 2 inventory

# Media

again, no OBS

# Additional context

what did engine update even DO other than introduce like eight bugs that arent even ee

**Comment by sleepyyapril** [comment]
> # Additional context
> what did engine update even DO other than introduce like eight bugs that arent even ee

it's to be expected with updating. bugs are fixable
