### ISSUE TITLE
Jittering displaces character, which is a lot more of a problem due to shake verb

### ISSUE THREAD

**Issue by bruhmogus** [Simple-Station/Einstein-Engines#1277]
# Description

The jittering function causes displacement for character visuals.

# Reproduction

1. Shake someone
2. Shake them more (optional)
3. Look at them being to the LEFT of the ssd indicator

# Expected behavior

1. Shake someone a lot
2. They return to normal location visually

# Media

![20241124112218_1](https://github.com/user-attachments/assets/251f62af-39a9-42c3-82df-37eda5d7b793)

![20241124112231_1](https://github.com/user-attachments/assets/91dfc8dc-7aa5-4132-8137-21fc7adad3da)

# Additional context

pick up that can

**Comment by Mnemotechnician** [comment]
The interaction verb is irrelevant, I blame the jittering system

**Comment by bruhmogus** [comment]
> The interaction verb is irrelevant, I blame the jittering system

true, i'll rename rq

**Comment by Mnemotechnician** [comment]
I figured it out in https://github.com/Fansana/floofstation1/pull/393, feel free to cherry pick it or something.

Fun fact:
![image](https://github.com/user-attachments/assets/0d99a3cc-1dfe-466d-8049-3600b87b7aa9)
