### ISSUE TITLE
Creatures capable of interacting via Alt+E

### ISSUE THREAD

**Issue by BlueHNT** [Simple-Station/Einstein-Engines#1308]
# Description

Currently, plenty of creatures can still interact with machinery as if they were players, while they 100% shouldn't be able to.

# Reproduction

1. Be creature
2. Alt+E freezer
3. Watch SM blow up

# Expected behavior

1. Be creature
2. Be unable to interact with freezer and break it
3. Watch SM blow up anyway

![image](https://github.com/user-attachments/assets/32746836-36d8-4984-abaf-11788ce3e2b5)

**Comment by sleepyyapril** [comment]
They are able to push a button, I honestly feel like this is fine. It's able to be fixed by making it a "complex interaction" check, but again, it's just pushing a power button.

**Comment by BlueHNT** [comment]
> They are able to push a button, I honestly feel like this is fine. It's able to be fixed by making it a "complex interaction" check, but again, it's just pushing a power button.

I feel like this button will at some point be a very critical button, but suit yourself.

**Comment by sleepyyapril** [comment]
> > They are able to push a button, I honestly feel like this is fine. It's able to be fixed by making it a "complex interaction" check, but again, it's just pushing a power button.
> 
> I feel like this button will at some point be a very critical button, but suit yourself.

Admin issue.

**Comment by BlueHNT** [comment]
> > > They are able to push a button, I honestly feel like this is fine. It's able to be fixed by making it a "complex interaction" check, but again, it's just pushing a power button.
> > 
> > 
> > I feel like this button will at some point be a very critical button, but suit yourself.
> 
> Admin issue.

If they are capable of doing it, they will do it. This is a dev issue.

**Comment by sleepyyapril** [comment]
It's not a dev issue when it makes sense for them to be able to press a button thoughhh

**Comment by BlueHNT** [comment]
I still believe it could be an issue since that stuff is easily abused the moment someone figures out a fun way to use it.

Needs more opinions

**Comment by sleepyyapril** [comment]
Xenos are, as of now, THE monster that would do this. In #1295, I added the check for whether the entity is able to do complex interactions. If you don't want it, remove Xeno's ComplexInteractions component.

It is the admins' job to keep bad users out, but they are incredibly smart in lore.

**Comment by BlueHNT** [comment]
Makes sense
