### ISSUE TITLE
Urist McDwarf entity is existant (it should not)

### ISSUE THREAD

**Issue by bruhmogus** [Simple-Station/Einstein-Engines#1389]
# Description

you can spawn urist mchands the dwarf even though we dont have dwarfs, 100% introduced by the surgery updates probably

# Reproduction

1. entity spawn
2. urist mchands the short ass mf

# Expected behavior

1. entity spawn
2. urist mchands the average size mf

# Media

![20241231164302_1](https://github.com/user-attachments/assets/09fd9ff8-8f12-4615-82a6-f7937fa4a6be)

# Additional context

aeiouuuuuuuuu

**Comment by stellar-novas** [comment]
This makes sense? Dwarves were not removed, they just aren't a selectable species in the character creation menu.

**Comment by angelofallars** [comment]
This has always been the case for disabled species. We don't delete them from the game, we just set the `roundStart` field in the species prototype to `false` so they can't be selected.

We also have Vox but they are not enabled anywhere like dwarves.

**Comment by bruhmogus** [comment]
> This has always been the case for disabled species. We don't delete them from the game, we just set the `roundStart` field in the species prototype to `false` so they can't be selected.
> 
> We also have Vox but they are not enabled anywhere like dwarves.

reopen, the entity was not present before the update

**Comment by stellar-novas** [comment]
I don't know what update to Shitmed you think did it, but I went back to a505ed782c2c9e868eea70b44ec24aa4d2b18698 and Urist the dwarf is spawnable.

**Comment by bruhmogus** [comment]
> I don't know what update to Shitmed you think did it, but I went back to [a505ed7](https://github.com/Simple-Station/Einstein-Engines/commit/a505ed782c2c9e868eea70b44ec24aa4d2b18698) and Urist the dwarf is spawnable.

that seems wrong, i could've sworn they werent spawnable before the goobmed

**Comment by gluesniffler** [comment]
as the shitmed guy i can confirm all i did to dwarves was add a comment, pass me some of that weed bruh
![image](https://github.com/user-attachments/assets/30548dbd-9209-49ee-8e4b-99d826b97f0a)
