### ISSUE TITLE
Failed to cherry-pick PR #26001: FIX Criminal SecHud icon Rsi path BUG

### ISSUE THREAD

**Issue by SimpleStation14** [Simple-Station/Einstein-Engines#149]
## Failed to cherry-pick PR: cannot create a tree from a not fully merged index.; class=Index (10); code=Unmerged (-10)
PR body below

###### `7bdfd4cfc0f4389fec675b5bb79c6bec3ead57dd`

PR opened by <img src="https://avatars.githubusercontent.com/u/152836416?v=4" width="16"/><a href="https://github.com/Baptr0b0t"> Baptr0b0t</a> at 2024-03-11 14:37:07 UTC
PR merged by <img src="https://avatars.githubusercontent.com/u/19864447?v=4" width="16"/><a href="https://github.com/web-flow"> web-flow</a> at 2024-03-11 14:45:30 UTC

---

PR changed 1 files with 5 additions and 5 deletions.

The PR had the following labels:
- No C#

---

<details open="true"><summary><h1>Original Body</h1></summary>

> 
> 
> 
> ## About the PR
> 
> I complete the path of the RSI texture for the icon of sechud (wanted/ detained/...) from criminal record
> ## Why / Balance
> 
> Fix bug
> ## Technical details
> 
> Complete the RSI texture path for criminal record
> ## Media
> 
> <img width="317" alt="image" src="https://github.com/space-wizards/space-station-14/assets/152836416/32815f37-3655-4567-8d15-f62919326270">
> 
> - [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
> 
> ## Breaking changes
> 
> 
> **Changelog**
> 
> 
> 
> - fix: Fix Sec Hud bugging out when criminal records are set on people.

</details>

**Comment by Mnemotechnician** [comment]
Wait, is this still not merged? This would explain #863.
