### ISSUE TITLE
Failed to cherry-pick PR #26163: Update Robust to v214.1.1

### ISSUE THREAD

**Issue by SimpleStation14** [Simple-Station/Einstein-Engines#222]
## Failed to cherry-pick PR: cannot create a tree from a not fully merged index.; class=Index (10); code=Unmerged (-10)
PR body below

###### `1e8f63df2ef286aa8d6be41287986fcc1b9f6354`

PR opened by <img src="https://avatars.githubusercontent.com/u/8107459?v=4" width="16"/><a href="https://github.com/PJB3005"> PJB3005</a> at 2024-03-16 00:15:14 UTC

---

PR changed  files with  additions and  deletions.

The PR had the following labels:
- No C#

---

<details open="true"><summary><h1>Original Body</h1></summary>

> Ack

</details>

**Comment by DEATHB4DEFEAT** [comment]
https://github.com/Simple-Station/Einstein-Engines/pull/394
