### ISSUE TITLE
Failed to cherry-pick PR #26190: Update engine to v214.2.0

### ISSUE THREAD

**Issue by SimpleStation14** [Simple-Station/Einstein-Engines#229]
## Failed to cherry-pick PR: cannot create a tree from a not fully merged index.; class=Index (10); code=Unmerged (-10)
PR body below

###### `00f05ef25eb67bc82cc2f0721c8bf777a4d5e80a`

PR opened by <img src="https://avatars.githubusercontent.com/u/60421075?v=4" width="16"/><a href="https://github.com/ElectroJr"> ElectroJr</a> at 2024-03-16 20:22:22 UTC

---

PR changed  files with  additions and  deletions.

The PR had the following labels:
- No C#

---

<details open="true"><summary><h1>Original Body</h1></summary>

> 

</details>

**Comment by DEATHB4DEFEAT** [comment]
https://github.com/Simple-Station/Einstein-Engines/pull/394
