### ISSUE TITLE
Bounties Don't Work

### ISSUE THREAD

**Issue by DangerRevolution** [Simple-Station/Einstein-Engines#25]
# Description

Inherited from Delta; where the tradepost now spawns in a different "instance" or FTL space; Bounties put into a crate and labelled are just sold as the value of the items in the crate rather than the whole bounty.

# Reproduction

1. Print bounty
2. Put bounty on crate
3. Put items in crate
4. Sell at trading post
5. Get basically nothing
6. Bounty incomplete

# Expected behavior

1. Print bounty
2. Put bounty on crate
3. Put items in crate
4. sell at trading post
5. get money
6. bounty complete

## If this can't be easily fixed then this change should be reverted.

**Comment by DebugOk** [comment]
Just revert 76d06416ab963cd487037e664e30a4853a73dbac for the easiest fix, or whatever the hash ends up being here

**Comment by Mnemotechnician** [comment]
This is outdated, bounties seem to work now. Should be closed unless it still happens somehow.

**Comment by DangerRevolution** [comment]
Fixed in this PR; and I've checked it's committed to EE
