### ISSUE TITLE
Failed to cherry-pick PR #26273: Fix Fland's Cargo Shuttle Atmos

### ISSUE THREAD

**Issue by SimpleStation14** [Simple-Station/Einstein-Engines#274]
## Failed to cherry-pick PR: cannot create a tree from a not fully merged index.; class=Index (10); code=Unmerged (-10)
PR body below

###### `395024a652f610e21d43f1faa9fb8ab49515e265`

PR opened by <img src="https://avatars.githubusercontent.com/u/110078045?v=4" width="16"/><a href="https://github.com/Nairodian"> Nairodian</a> at 2024-03-19 23:23:40 UTC

---

PR changed 1 files with 20 additions and 37 deletions.

The PR had the following labels:
- No C#

---

<details open="true"><summary><h1>Original Body</h1></summary>

> ## About the PR
> Ran fixgridatmos on Fland's cargo shuttle map.
> 
> ## Why / Balance
> It was bugged and caused people to die to lack of pressure/air before.
> 
> ## Media
> - [x] This PR does not require an ingame showcase.
> 
> **Changelog**
> Should be noticeable enough not to warrant one.

</details>

**Comment by VMSolidus** [comment]
We shouldn't need PRs to maps that aren't in this codebase, I'm going to go ahead and close this issue.
