### ISSUE TITLE
Failed to cherry-pick PR #26316: remove rped

### ISSUE THREAD

**Issue by SimpleStation14** [Simple-Station/Einstein-Engines#294]
## Failed to cherry-pick PR: cannot create a tree from a not fully merged index.; class=Index (10); code=Unmerged (-10)
PR body below

###### `5ac88d9b2788182f607aeaf08eea8d26b1bb4d18`

PR opened by <img src="https://avatars.githubusercontent.com/u/39013340?v=4" width="16"/><a href="https://github.com/deltanedas"> deltanedas</a> at 2024-03-21 20:14:32 UTC

---

PR changed 6 files with 3 additions and 45 deletions.

The PR had the following labels:
- No C#
- Status: Needs Review

---

<details open="true"><summary><h1>Original Body</h1></summary>

> ## About the PR
> remove rped item recipe and tech
> 
> ## Why / Balance
> its useless
> if someone wanted to make it not useless they had plenty of time, it just wastes points right now
> 
> ## Technical details
> no
> 
> ## Media
> - [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
> 
> ## Breaking changes
> no
> 
> **Changelog**
> no cl no fun

</details>

**Comment by VMSolidus** [comment]
No. Not going to remove it. And not going to cherrypick its removal. Closing since Issue since it goes against our current upstream merge policy. 
![faridaiscute](https://github.com/Simple-Station/Einstein-Engines/assets/16548818/51617838-9ca3-477d-b469-6b4c2e0c134f)
