### ISSUE TITLE
Failed to cherry-pick PR #26305: FTL UIScale fixes

### ISSUE THREAD

**Issue by SimpleStation14** [Simple-Station/Einstein-Engines#295]
## Failed to cherry-pick PR: 1 uncommitted change would be overwritten by merge; class=Merge (22); code=Conflict (-13)
PR body below

###### `000a259563fd6ac1ec6889cd1fc767fcbc4a39de`

PR opened by <img src="https://avatars.githubusercontent.com/u/31366439?v=4" width="16"/><a href="https://github.com/metalgearsloth"> metalgearsloth</a> at 2024-03-21 13:30:55 UTC

---

PR changed 2 files with 8 additions and 7 deletions.

The PR had the following labels:
- Changes: UI

---

<details open="true"><summary><h1>Original Body</h1></summary>

> - Fix text drawing being offset.
> - Fix beacon snapping and distance check.
> - Fix DrawData being offset.
> - Fix bounds check for map objects not using PixelSize.
> 
> Resolves https://github.com/space-wizards/space-station-14/issues/26028
> 
> :cl:
> - fix: Fix some shuttle console stuff surrounding the Map screen.

</details>

**Comment by VMSolidus** [comment]
Already cherry-picked this
