### ISSUE TITLE
Failed to cherry-pick PR #26326: bagel update

### ISSUE THREAD

**Issue by SimpleStation14** [Simple-Station/Einstein-Engines#297]
## Failed to cherry-pick PR: cannot create a tree from a not fully merged index.; class=Index (10); code=Unmerged (-10)
PR body below

###### `596f9a6c2c6399ef658493f49fec3b5ecc84eccf`

PR opened by <img src="https://avatars.githubusercontent.com/u/99158783?v=4" width="16"/><a href="https://github.com/Emisse"> Emisse</a> at 2024-03-22 03:13:01 UTC

---

PR changed 1 files with 202 additions and 296 deletions.

The PR had the following labels:
- No C#
- Changes: Map

---

<details open="true"><summary><h1>Original Body</h1></summary>

> changelog
> -move the chem maint door and apc 
> -skub
> 

</details>

**Comment by VMSolidus** [comment]
No need to update maps not present on this repo
