### ISSUE TITLE
Languages from Frontier

### ISSUE THREAD

**Issue by VMSolidus** [Simple-Station/Einstein-Engines#37]
# Description

Another minor feature, but one still essential to have. Frontier is currently working on an implementation of character languages, beyond just the one originally created for Vulpkanin. This feature is not referring to the canilunzt translator item, this is instead referring to the ability to select languages in character creation, allowing characters to start the game knowing certain languages. Which helps add key lore ties to characters. This is a bit of a lower priority feature, but will also come hand in hand with the creation of our own Common Core Lore Document. 

Since it very well won't make sense to people to say that their character speaks Sol Common, if there is no context to what Sol Common even is. Also useful is that this feature enables the ability for characters to "Speak" and understand Sign Language, something that has been very long requested by a great number of people.

**Comment by FoxxoTrystan** [comment]
https://github.com/Simple-Station/Einstein-Engines/pull/43
