### ISSUE TITLE
Make CPR real again.

### ISSUE THREAD

**Issue by Adrian16199** [Simple-Station/Einstein-Engines#49]
# Description

Please, for the love of oracle, provide me with the lost love that I have been waitin to see again.

The CPR feature from nyano
When in critical condition: instead of hugging, you would perform CPR that would heal oxygen damage and stop loss of oxygen
If not done by a doctor, it would have a chance to break the patient's ribcage
# Media

**Comment by Elijahrane** [comment]
something needs to be done to more elegantly solve all the empty hand interact conflicts -- my solution wasn't very pretty. the rest of it was fine though

**Comment by DangerRevolution** [comment]
Is it time to make intents real?? :O

**Comment by Elijahrane** [comment]
no some stuff just NEEDS ordered handling to not be shit -- all that stuff would be under help intent anyway under intents
