### ISSUE TITLE
DeltaV tag in the main options menu

### ISSUE THREAD

**Issue by DangerRevolution** [Simple-Station/Einstein-Engines#494]
# Description

Resources/Locale/en-US/deltav/escape-menu/options-menu.ftl

I want Goldfish crackers

# Media

![image](https://github.com/Simple-Station/Einstein-Engines/assets/142105406/0b60e1a7-f5d1-445b-b8ac-d23d9ca90e45)

**Comment by DEATHB4DEFEAT** [comment]
guh, duplicate of https://github.com/Simple-Station/Einstein-Engines/issues/481, which you also made
