### ISSUE TITLE
Players do *not* like being forcibly zoomed in when playing as a shorter character.

### ISSUE THREAD

**Issue by DangerRevolution** [Simple-Station/Einstein-Engines#496]
# Description

Title. Another solution needs to be made; either an equally bad side effect or just limiting vision instead of forcibly zooming a player in.

**Comment by redmushie** [comment]
Big +1 from me. This behavior caught me and others really off guard. It just doesn't seem very desirable either; especially so if you want to play Security.

**Comment by redmushie** [comment]
I found out this can easily be disabled via server settings:

![image](https://github.com/user-attachments/assets/40dea411-f93b-460e-8faa-08ddf8ad94d2)

Put this in your `server_config.toml` / `config.toml`: 
![image](https://github.com/user-attachments/assets/857bfdf5-4ba4-44cf-931a-457a118431f5)

**Comment by redmushie** [comment]
Default value for `heightadjust.modifies_zoom` has been changed to `false` by #564. This issue can be closed.

**Comment by DangerRevolution** [comment]
I'll reformat the issue to be more of "The true value needs to be better" or smth

**Comment by DangerRevolution** [comment]
Issue bandaided by #564, probably still needs some sort of other solution IMO?
