### ISSUE TITLE
Weight and Height need calibration.

### ISSUE THREAD

**Issue by DangerRevolution** [Simple-Station/Einstein-Engines#497]
# Description

Title. Calibration is needed to reign in **wacky** designs; (primarily that width slider) from making pencil-thin characters that are mega-squashed.

**Comment by Mnemotechnician** [comment]
Agreed, the aspect ratio of characters should be restricted to something in some range like 0.7-1.3. I.e. the minimum/maximum width of a character should depend on their current height.
