### ISSUE TITLE
Accessory object tracker time issue

### ISSUE THREAD

**Issue by BlueHNT** [Simple-Station/Einstein-Engines#568]
# Description

When hovering over accessory items in the customization bar that require time. The time given in highlight is incorrect and shows 0.
This applies to items which use `!type:CharacterPlaytimeRequirement` with `tracker:` and `min:` from my findings specifically.

# Media

Example from N14 which uses EE upstream:

![image](https://github.com/user-attachments/assets/f5578401-c382-4d22-ab7f-c50ce3ee8586)
![image](https://github.com/user-attachments/assets/e59abf89-eb0c-4dc6-9df1-70e42448db2d)

**Comment by DEATHB4DEFEAT** [comment]
Fixed by https://github.com/Simple-Station/Einstein-Engines/pull/584
