### ISSUE TITLE
Remove Or Rework Vulpkanin

### ISSUE THREAD

**Issue by VMSolidus** [Simple-Station/Einstein-Engines#711]
# Description

I think I'm going to make this official here, and give this as a 2-Weeks Notice. The general standard we'd like to have for Species on EE is that species must be sufficiently mechanically unique that they can justify their own existence. Having a species be fundamentally just a reskinned human with no actual code behind it isn't really going to fly. With that in mind, Vulpkanin are currently on the chopping block, unless someone can come up with a PR within the next 2 weeks that fundamentally reworks Vulpkanin with a sufficiently unique C# system. 

Vulpkanin aren't going to be fully "removed" in the event that nobody can come forward with a satisfactory enough PR. Instead what we're going to do is merge Vulpkanin with Felinid, making the two into a combined "Kemo/Mutant" species. If one wishes to play a Vulpkanin like before, they need only put the appropriate Vulp markings on their character. Naturally this also means that for the Nyano veterans in the crowd, you could quite feasibly play a Cynocephalus by omitting the tail, and adding a full dog head to an otherwise unmodified Human. 

The remaining "Features" Vulpkanin had are so trivial and minor, that they can simply be made into a 0 point "Canine-Mutant" trait, which gives a character things like the dog voicelines, the vulpkanin-unique clothing sprites, and so on.  

# Potential Ideas for Reworking Vulpkanin

**Scent System?**
- Innate air analyzer?
- Track people by sniffing scents(fingerprints)?
- Identify drugs by scent?

**Toggleable Night Vision?**

**Metabolic Shennanigans?**
- Spend hunger saturation for bursts of speed boost
- Increased metabolic rates(Drugs, food, poison, water, etc.
- Flash vulnerability
- Loud sound vulnerability?

**Comment by FoxxoTrystan** [comment]
DarkVision was something with flash vunerability.

Tho darkvision need to be made at first for that.

Orignially, Languages was made for vulps but now its feature that now a trait "Forigner"

**Comment by angelofallars** [comment]
These are the number tweak ideas I got after some discussion, to go along with a potential scent system:
- 30% less Cold damage
- 30% more Heat
- Firestacks decrease slower OR increase faster
- Voracious trait by default
- 15% more hunger
- Blinded longer by flashes
- More eye damage
- Blinded a little by flashes

**Comment by VMSolidus** [comment]
> These are the number tweak ideas I got after some discussion, to go along with a potential scent system:
> 
>     * 30% less Cold damage
> 
>     * 30% more Heat
> 
>     * Firestacks decrease slower OR increase faster
> 
>     * Voracious trait by default
> 
>     * 15% more hunger
> 
>     * Blinded longer by flashes
> 
>     * More eye damage
> 
>     * Flashes cause slight eye damage

Excellent, this can actually also be a separate PR from one that introduces the ScentSystem.

**Comment by angelofallars** [comment]
Yes, I'm planning on making it a separate PR.

**Comment by DEATHB4DEFEAT** [comment]
Closed*

**Comment by FoxxoTrystan** [comment]
Make an issue like this again and im doing to delete your kneecaps

**Comment by VMSolidus** [comment]
> Make an issue like this again and im doing to delete your kneecaps

Nah next time I'm going to PR the removal of YOUR kneecaps. :)

**Comment by DEATHB4DEFEAT** [comment]
> Make an issue like this again and im doing to delete your kneecaps

Issue issues will continue until morale is gone :trollface:

**Comment by DEATHB4DEFEAT** [comment]
no idea how I did that

**Comment by ShatteredSwords** [comment]
Reopening it just for a split second was some advanced github trolling

**Comment by VMSolidus** [comment]
> no idea how I did that

![90cthf](https://github.com/user-attachments/assets/df834df0-b201-453d-8365-eec1897cbb1f)

**Comment by FoxxoTrystan** [comment]
I will turn harpy into a simplemob like chicken.
