### ISSUE TITLE
Loadouts / Traits / Character Requirements mega-issue

### ISSUE THREAD

**Issue by DangerRevolution** [Simple-Station/Einstein-Engines#723]
# Description

As requested and spoken about:

## Problems:

- [ ] test fail should be thrown if using an invalid ID inside a loadout entry
- [ ] Categories will overflow the UI if there's too many, or a user's screen is too small
- [ ] Selecting an item you fit the requirements for; then failing to meet the requirements should de-select the item (or something similar)
- [ ] Traits / Loadouts will reset scroll upon any update
- [ ] Traits / Loadouts you do not meet the requirements for; that you then switch to meet the requirements will not update the entry until Loadouts / traits is updated
i.e if I'm an Oni, and I want a Felinid trait so I switch to Felinid; the trait menu won't update until I do something to update it 

## Problems (needs replicating or testing)

- [x]  Whitelist doesn't work
- [ ]  JobBans don't work
- [ ]  AntagBans don't work (Wizden issue, there's a PR open to fix this but I doubt it'd work for us)
- [ ] Weight on the CharacterProfile and the Entity don't match up. (ask MnemoTechnician)

### Requested Features

- [ ] OrRequirements
i.e I need to be a Human, OR a Felinid to be Captain
- [ ] Requirements
	- [ ] Height
	- [ ] Width
	- [ ] Weight
	- [ ] Gender
	- [ ] Sex
	- [ ] Markings
- [ ] https://github.com/Simple-Station/Einstein-Engines/pull/643

I will add more as I remember them, it's quite late

**Comment by VMSolidus** [comment]
Also help me with this. It has SEVERE performance issues that I lack the knowledge to solve.
https://github.com/Simple-Station/Einstein-Engines/pull/643

**Comment by VMSolidus** [comment]
@DangerRevolution 
 - Serialized Exclusive Groups IE: Make a group with the name "Smokes", and if you select an item with the ExclusiveGroup "Smokes" it automatically hides all other items in said ExclusiveGroup.
 - Reset Loadouts button
 - Requirements on Jobs only update when you first join the server. EG: If I have a job that only allows Human, if my character selected upon joining the server was a Harpy, I now cannot join that job even if I change characters to a Human.
