### ISSUE TITLE
Thief Item Set Not Given, Ninja Jetpack Missing on Spawn

### ISSUE THREAD

**Issue by v0idRift** [Simple-Station/Einstein-Engines#738]
# Description

There is an issue where the thief's item set is not being given, and the ninja is not receiving a jetpack in hand upon spawning, even though it is listed in the set.

# Reproduction

1. Spawn as a thief.
2. Notice that the item set is not received.
3. Spawn as a ninja.
4. Observe that the ninja does not have a jetpack in hand.

# Expected Behavior

1. The thief should receive the complete item set upon spawning.
2. The ninja should have the jetpack in hand when spawning.

# Additional Context

There might be an issue with the loadout configuration or the spawning script. Related to https://github.com/Simple-Station/Einstein-Engines/pull/734

**Comment by v0idRift** [comment]
I see gear fixed here but not understand much how
https://github.com/WWhiteDreamProject/wwdpublic/pull/14

maybe someone can look at it

**Comment by Evgencheg** [comment]
This is fixed...

**Comment by Remuchi** [comment]
was fixed
