### ISSUE TITLE
Insufficient Player Count for Selected Game Mode Causes Round Restart Loop, Preventing New Rounds from Starting

### ISSUE THREAD

**Issue by v0idRift** [Simple-Station/Einstein-Engines#745]
# Description
There is an issue when selecting certain game modes in the lobby, specifically "Nuclear Operatives" or "Traitor" (tested on these modes, but likely affects others as well). If you wait for the timer to expire without pressing "Ready," the round restarts without switching to fallback modes, and no errors are reported. The next round simply does not start; instead, a message stating "The round will start soon" is displayed indefinitely. After this occurs, no game mode or map can be launched, and the server must be shut down. Even using `forcepreset Extended` won't start the round.

# Reproduction
1. Open the game.
2. Select the "Nuclear Operatives" or "Traitor" game mode in the lobby.
3. Wait for the timer to expire without pressing "Ready."
4. Observe that the round does not start and no fallback modes are triggered.

# Expected Behavior
1. The round should start normally after the timer expires, or fallback modes should be triggered if the original mode cannot be started.

# Media
![image](https://github.com/user-attachments/assets/f1ec9ff4-c0fe-4163-95b5-f4b5fa368eb7)

# Additional Context
This issue was tested on both the main server with players and the dev build. After the issue occurs, no further rounds can be started until the server is restarted.

**Comment by ShatteredSwords** [comment]
I assume #749 solves this issue now
