### ISSUE TITLE
Listening Outpost Adds Gamerules

### ISSUE THREAD

**Issue by ShatteredSwords** [Simple-Station/Einstein-Engines#764]
# Description

Listening Outpost starts Traitor Gamemode also also starts an event scheduler?

# Reproduction

1. Listening Outpost Spawns
2. Someone picked the Listening Outpost ghost role
3. Traitor Gamerule Starts
4. Possibly also starts an event scheduler

# Expected behavior

1. Listening Outpost Spawns
2. Someone picks the Listening Outpost ghost role
3. Gamerules stay the same (other than the listening outpost)

# Additional context

This was/is an issue in DeltaV, and I have no idea if they've solved it there or not

**Comment by VMSolidus** [comment]
This *was* an issue on this codebase, until we reverted the Antag Refactor cherry-pick. We'll revisit antag refactor at a later time when we are ready to actually do another mass cherry-pick. DeltaV does have fixes for the Listening Outpost for the Antag Refactor, and we'll likely cherry-pick said fixes when the time is right.
