### ISSUE TITLE
Issue with psionic power telegnosis

### ISSUE THREAD

**Issue by Evgencheg** [Simple-Station/Einstein-Engines#821]
# Description

# Reproduction
1. Have an telegnosis
2. Use telegnosis
3. Cant go back

# Expected behavior
You can go back after telegnosis

# Media
![image](https://github.com/user-attachments/assets/8775d7e4-7e96-47e9-bac2-95e96d56aa00)

**Comment by VMSolidus** [comment]
Known issue, solved by https://github.com/Simple-Station/Einstein-Engines/pull/795
But my maintainers haven't approved it yet.
