### ISSUE TITLE
Bug with deep fryer

### ISSUE THREAD

**Issue by Evgencheg** [Simple-Station/Einstein-Engines#825]
# Description
You can put ALL in deep fryer

# Reproduction
1. Put something in deepfryer, not food

# Expected behavior
1. You can only put food in deep fryer

# Media
![image](https://github.com/user-attachments/assets/61784054-dbfe-4a43-ba97-33abdb75d173)

**Comment by VMSolidus** [comment]
Completely intended. You're supposed to be able to deep fry "Almost" anything. This includes things like Firearms, The Captain's ID, Animals(That you can pick up), paper, etc. The only things you can't deep fry are things you can't pick up, and the Nuke Disk(for gamemode safety reasons)

**Comment by VMSolidus** [comment]
In SS13, where the Deep Fryer came from, it was considered a rite of passage for Secoffs to get robusted by a clown, and have their stun baton deep fried. We have preserved this behavior here.

**Comment by Evgencheg** [comment]
> The only things you can't deep fry are things you can't pick up, and the Nuke Disk(for gamemode safety reasons)
but i put here the computer xDD

**Comment by VMSolidus** [comment]
> > The only things you can't deep fry are things you can't pick up, and the Nuke Disk(for gamemode safety reasons)
> 
> but i put here the computer xDD

I happen to know that in order to do so, you needed to disable its BodyType.Static, as well as VVEdit the computer to have an ItemComponent, so you had to bypass several tests for "Can this actually fit in the basket" to deep fry that computer. :)

**Comment by Evgencheg** [comment]
> > > The only things you can't deep fry are things you can't pick up, and the Nuke Disk(for gamemode safety reasons)
> > 
> > 
> > but i put here the computer xDD
> 
> I happen to know that in order to do so, you needed to disable its BodyType.Static, as well as VVEdit the computer to have an ItemComponent, so you had to bypass several tests for "Can this actually fit in the basket" to deep fry that computer. :)

Oh... KK.
