### ISSUE TITLE
bug with onwall Geiger counter

### ISSUE THREAD

**Issue by Evgencheg** [Simple-Station/Einstein-Engines#827]
# Description
onwall Geiger counter doesnt work

Description

# Reproduction
1. Have radiation near onwall Geiger counter and Geiger counter
2. Check rads

# Expected behavior
1. Use onwall geiger counter and it have radiation near

# Media
![image](https://github.com/user-attachments/assets/59bcd070-e0ef-492e-8ebe-b813e46a32e3)
![image](https://github.com/user-attachments/assets/db02e4af-93c3-40a1-b8b7-fd2f7aa1829d)

# Additional context
Translation:
1 media - onwall Geiger counter, 0.0 rads
2 media - Geiger counter, 4.7 rads

**Comment by stellar-novas** [comment]
The wall itself might be blocking the radiation, try placing it on a window?

**Comment by Evgencheg** [comment]
> The wall itself might be blocking the radiation, try placing it on a window?

maybe... letme check

**Comment by Evgencheg** [comment]
> The wall itself might be blocking the radiation, try placing it on a window?

yeah, wall blocking

**Comment by VMSolidus** [comment]
Since the onwall Geiger counter works by measuring how much radiation damage it's receiving, if any surface is reducing radiation damage, (including the wall it's on), the onwall Geiger will show this reduced amount. Generally when I map these, I try to put the onwall Geigers on top of a surface that doesn't block significant amounts of radiation, such as non-plasma windows, and as close to the potential radiation source area as possible.

**Comment by stellar-novas** [comment]
Hmm.
Could we move the detector to the edge of the tile so mappers could choose (by rotating/mirror flipping) if it should be measuring "rads in the chamber" or "rads in the observation area"?

**Comment by Evgencheg** [comment]
> Hmm. Could we move the detector to the edge of the tile so mappers could choose (by rotating/mirror flipping) if it should be measuring "rads in the chamber" or "rads in the observation area"?

yea, good idea...

**Comment by dvir001** [comment]
We have code on Frontier to offset wall mount jukebox to offset so the music wont be coming from the wall itself, I think the same logic can be added here to offset the rad collector zone from it.
