### ISSUE TITLE
bug with jetpack ninja

### ISSUE THREAD

**Issue by Evgencheg** [Simple-Station/Einstein-Engines#828]
# Description
Ninja dont have jetpack but code have... I dont edited it
# Reproduction
1. Spawn as ninja

# Expected behavior
1. Spawn as ninja and fly with jetpack 🥷

# Media
![image](https://github.com/user-attachments/assets/e38b7ff5-525b-4987-9e51-8db2428472a7)
![image](https://github.com/user-attachments/assets/569c3aa6-e710-498c-99f1-d8c84c4a5da8)

**Comment by v0idRift** [comment]
https://github.com/Simple-Station/Einstein-Engines/issues/738

**Comment by Mnemotechnician** [comment]
This and #738 appear to have been fixed after the antag refactor.
