### ISSUE TITLE
Bug with interaction system

### ISSUE THREAD

**Issue by Evgencheg** [Simple-Station/Einstein-Engines#836]
# Description
All interactions can be used through windows

# Reproduction
1. Try to interact through windows.

# Expected behavior
1. You cant interact through windows...

# Media
https://github.com/user-attachments/assets/29f724b6-3e03-494e-9bfa-e69a4ec3aac5

**Comment by Mnemotechnician** [comment]
Does this happen with all windows or just directional ones? The latter were always buggy...

**Comment by Evgencheg** [comment]
> atter

directional... I know this hard to fix but... maybe some way to?
