### ISSUE TITLE
Criminal Records Bug

### ISSUE THREAD

**Issue by Flybik** [Simple-Station/Einstein-Engines#971]
# Description
When using the console of creminalistic records, a lot of errors are received in the Client console. Because of this, the game slows down and the role icons are not visible.

A clean version of the client was used.

# Reproduction
1. Open game.
2. Enter the round.
3. Put anyone on the wanted list or set a status in the Criminal Records console.

# Expected behavior
FPS drops, console will show errors, job icons disappear

# Media

Video: https://youtu.be/lOoFvnYeU7s
Log: [error status icon.log](https://github.com/user-attachments/files/17171358/error.status.icon.log)

**Comment by VMSolidus** [comment]
I think this bug *might* have been fixed since it was related to a job icon error, and we've merged fixes for said errors. I'd have to double check though.

**Comment by Mnemotechnician** [comment]
Yea, should've been fixed as a part of #1087

**Comment by Remuchi** [comment]
Yeah should be fixed judging by the error and the fix provided in PR.
