### ISSUE TITLE
Arachnes cannot drain blood from cocoons without taking damage

### ISSUE THREAD

**Issue by Crono209ggg** [Simple-Station/Einstein-Engines#975]
When an Arachne tries to drain blood from cocoons, they start vomiting and take poison damage due to the blood they consumed, and it doesn't make any sense

https://github.com/user-attachments/assets/d2c7f358-c9ef-4f31-b634-9d90923bb4a1

**Comment by Evgencheg** [comment]
Same problem with oneirophag
