### ISSUE TITLE
damage bug

### ISSUE THREAD

**Issue by Evgencheg** [Simple-Station/Einstein-Engines#979]
# Description
Blue/red damage layer forces to keep on player

# Reproduction
1. Get damage and get blue/red layer

# Expected behavior
1. Get damage and dont get blue/red layer

# Media
![image](https://github.com/user-attachments/assets/5ba0c682-f059-4ca3-a9c7-6796edda3775)

**Comment by VMSolidus** [comment]
I'm unable to replicate this on current EE Master.
